[package]
name = "pinky-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "pinky_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4", features = [] }

[dependencies]
pinky-core = { path = "../../../crates/pinky-core" }
serde.workspace = true
tokio.workspace = true
uuid.workspace = true
zeroize = "1"
tauri = { version = "2.8", features = [] }
